# Package preinstall docker ce.
- name: Install | install apt-transport-https
  become: true
  apt: pkg=apt-transport-https update-cache=yes
  tags: pre-install-docker

- name: Install | install ca-certificates
  become: true
  apt: pkg=ca-certificates update-cache=yes
  tags: pre-install-docker

- name: Install | install curl
  become: true
  apt: pkg=curl update-cache=yes
  tags: pre-install-docker

- name: Install | install gnupg-agent
  become: true
  apt: pkg=gnupg-agent update-cache=yes
  tags: pre-install-docker    

- name: Install | install software-properties-common
  become: true
  apt: pkg=software-properties-common update-cache=yes
  tags: pre-install-docker